### ISSUE TITLE
2009 year doesn't work

### ISSUE THREAD

**Issue by waldoj** [openva/attorney-analysis#12]
When I set `case_year = '2009'`, after I pass the CAPTCHA, I receive this error:

```
Traceback (most recent call last):
  File "process-cases.py", line 72, in <module>
    partial_cases = load_case_file(partial_cases_file_path)
  File "process-cases.py", line 23, in load_case_file
    row['FILE_DATE'] = parse_datetime(row['FILE_DATE'])
  File "process-cases.py", line 10, in parse_datetime
    return datetime.strptime(date, "%m/%d/%y")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%m/%d/%y'
```

Is it possible `case_year` is being naively parsed at some point, and there's a presumption of `201?` format?

OTOH, with just one case, maybe I should just look this up manually. :)

**Comment by bschoenfeld** [comment]
Yeah. The file has a number of empty rows. We should just remove the bad rows instead of checking for valid data.

**Comment by waldoj** [comment]
Ah-ha—of course that's the problem. :) Thanks!
